#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

manifest:
  version: "0.13"

  projects:
    - name: sdk-edge-ai
      url: https://github.com/nrfconnect/sdk-edge-ai
      path: sdk-edge-ai
      revision: v2.1.0
      import: true

  self:
    path: matter-edge-ai
